/**
 * remotion-render-probe.ts — end-to-end proof: codegen -> bundle -> renderMedia
 * -> MP4 on disk, for a few generated motion-graphics kinds.
 */
import * as fs from 'fs';
import * as path from 'path';
import { authorRemotionComponent, type MotionKind } from '../src/agentic/media/remotion-codegen.js';

const OUT = path.resolve('workspace/remotion-render-probe');
const PICKS: { kind: MotionKind; id: string; label: string }[] = [
    { kind: 'kinetic', id: 'Scene0', label: 'kinetic text' },
    { kind: 'infographic', id: 'Scene1', label: 'animated bar chart' },
    { kind: 'particle', id: 'Scene2', label: 'particle field' },
    { kind: 'spectrum', id: 'Scene3', label: 'audio spectrum' },
];

async function main() {
    fs.mkdirSync(OUT, { recursive: true });
    fs.mkdirSync(path.join(OUT, 'out'), { recursive: true });

    console.log('=== codegen ===');
    PICKS.forEach((p, i) => {
        const src = authorRemotionComponent({
            index: i,
            kind: p.kind,
            title: p.kind === 'infographic' ? 'REVENUE GROWTH' : 'AGENTIC MOTION',
            caption: 'generated by remotion-codegen',
            data: [42, 68, 55, 91, 76],
            labels: ['Q1', 'Q2', 'Q3', 'Q4', 'Q5'],
            palette: ['#0a0a12', '#FF6B35', '#4CC9F0'],
            durationInFrames: 60,
            width: 1280,
            height: 720,
        });
        fs.writeFileSync(path.join(OUT, `scene_${i}.tsx`), src, 'utf8');
        console.log(`  ${p.id} (${p.label}) -> ${src.length} chars`);
    });

    const imports = PICKS.map((p, i) => `import { Scene${i} } from './scene_${i}';`).join('\n');
    const comps = PICKS.map(
        (p, i) => `      <Composition id="${p.id}" component={Scene${i}} durationInFrames={60} fps={30} width={1280} height={720} />`,
    ).join('\n');
    fs.writeFileSync(
        path.join(OUT, 'Root.tsx'),
        `import React from 'react';\nimport { Composition } from 'remotion';\n${imports}\n\nexport const RemotionRoot: React.FC = () => (\n  <>\n${comps}\n  </>\n);\n`,
        'utf8',
    );
    fs.writeFileSync(
        path.join(OUT, 'index.ts'),
        `import { registerRoot } from 'remotion';\nimport { RemotionRoot } from './Root';\n\nregisterRoot(RemotionRoot);\n`,
        'utf8',
    );

    const { bundle } = await import('@remotion/bundler');
    const { renderMedia, selectComposition, renderStill } = await import('@remotion/renderer');

    console.log('\n=== bundle ===');
    const t0 = Date.now();
    const serveUrl = await bundle(path.join(OUT, 'index.ts'), () => undefined, { webpackCacheDisabled: true });
    console.log('  ok', Date.now() - t0, 'ms');

    console.log('\n=== renderMedia (MP4 per motion kind) ===');
    for (const p of PICKS) {
        const mp4 = path.join(OUT, 'out', `${p.id}.mp4`);
        try {
            const composition = await selectComposition({ serveUrl, id: p.id, inputProps: {} });
            const t = Date.now();
            await renderMedia({
                composition,
                serveUrl,
                codec: 'h264',
                outputLocation: mp4,
                concurrency: 2,
                imageFormat: 'jpeg',
                timeoutInMilliseconds: 1000 * 60 * 5,
            });
            const st = fs.existsSync(mp4) ? fs.statSync(mp4) : null;
            console.log(
                `  ${p.id.padEnd(7)} OK  ${st ? (st.size / 1024).toFixed(0) + ' KB' : 'no file'}  ${Date.now() - t} ms`,
            );
        } catch (e: any) {
            console.log(`  ${p.id.padEnd(7)} FAIL ${String(e.message).split('\n')[0].slice(0, 120)}`);
        }
    }

    console.log('\n=== renderStill (generated IMAGE via Remotion) ===');
    try {
        const composition = await selectComposition({ serveUrl, id: 'Scene1', inputProps: {} });
        const png = path.resolve('input/visuals/remotion_generated_cover.png');
        fs.mkdirSync(path.dirname(png), { recursive: true });
        await renderStill({ composition, serveUrl, output: png, frame: 45 });
        const st = fs.statSync(png);
        console.log(`  OK ${(st.size / 1024).toFixed(0)} KB -> ${png}`);
    } catch (e: any) {
        console.log(`  FAIL ${String(e.message).split('\n')[0].slice(0, 140)}`);
    }
}

main().catch((e) => {
    console.error('PROBE FAILED:', e);
    process.exit(1);
});
